on: [push]

jobs:
  tag_release:
    runs-on: ubuntu-latest
    name: Tag release
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tag version
        uses: wendbv/calver-tag-action@main
        with:
          output-only: true
        id: tag-version
      - name: Get the output version
        run: echo "The new version is ${{ steps.tag-version.outputs.version }}"
